# Site settings
title: You're awesome title
email: who@me.com
description: > # this means to ignore newlines until "baseurl:"
 Jekyll Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://vyk.netlify.com" # the base hostname & protocol for your site
twitter_username: vyk
github_username:  vyk

# Build settings
markdown: kramdown
